<?php
/** @var Magento\Framework\Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var Denal05\MacademyM2CodingKickstartBlog\ViewModel\Post $postViewModel */
$postViewModel = $block->getData('post_viewmodel');
$post = $postViewModel->getDetail();
?>
<div class="blog-post-detail">
    <h1><?= $escaper->escapeHtml($post->getTitle()) ?></h1>
    <p><em><?= __('Created at: %1', $post->getCreatedAt()) ?></em></p>
    <p><?= $escaper->escapeHtml($post->getContent(), ['em', 'p', 'strong']) ?></p>
</div>
