<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Denal05\MacademyM2CodingKickstartBlog\ViewModel\Post $postViewmodel */
$postViewmodel = $block->getData('post_viewmodel');
?>
<div class="blog-post-list">
    <h1><?= __('Blog posts') ?></h1>
    <ul>
        <?php foreach ($postViewmodel->getList() as $post): ?>
            <li><a href="<?= $block->getUrl('blog/post/detail', ['id' => $post->getData('id')]) ?>"
                ><?= $post->getData('title') ?></a></li>
        <?php endforeach ?>
    </ul>
    <p><?= __('Post count: %1', $postViewmodel->getCount()) ?></p>
</div>
